from abc import ABC, abstractmethod
import numpy as np
from typing import List, Dict, Any

class BaseDetector(ABC):
    """
    Abstract base class for all object detectors in the pipeline.
    Ensures that any detector implementation follows the same input/output contract.
    """
    
    @abstractmethod
    def detect(self, frame: np.ndarray) -> np.ndarray:
        """
        Process a frame and return bounding box detections.
        
        Args:
            frame (np.ndarray): The image frame from OpenCV.
            
        Returns:
            np.ndarray: Detections in the format [x1, y1, x2, y2, confidence, class_id].
                        Returns an empty array of shape (0, 6) if nothing is detected.
        """
        pass

class BaseTracker(ABC):
    """
    Abstract base class for all object trackers (e.g., BoT-SORT, ByteTrack).
    """
    
    @abstractmethod
    def update(self, detections: np.ndarray, frame: np.ndarray) -> List[Dict[str, Any]]:
        """
        Update the tracker with new detections and return tracked objects.
        
        Args:
            detections (np.ndarray): The array generated by BaseDetector.detect().
            frame (np.ndarray): The current video frame (some trackers need visual features).
            
        Returns:
            List[Dict[str, Any]]: A standardized list of dictionaries containing:
                                  - 'bbox': [x1, y1, x2, y2]
                                  - 'track_id': int
                                  - 'confidence': float
                                  - 'class_id': int
        """
        pass